#!/usr/bin/env bash
set -euo pipefail

ENV_NAME="${ENV_NAME:-grinnder}"
ROOT="${ROOT:-data}"
OUTPUT="${OUTPUT:-docs/products_grinnder_gcn_h256_e10.csv}"
SUMMARY="${SUMMARY:-docs/products_grinnder_gcn_h256_e10_summary.md}"
PARTS="${PARTS:-1,2,4}"
EPOCHS="${EPOCHS:-10}"
HIDDEN="${HIDDEN:-256}"
DEVICE="${DEVICE:-cuda:0}"
HOST_MEMORY_BUDGET_GB="${HOST_MEMORY_BUDGET_GB:-0.0}"
SKIP_BENCH="${SKIP_BENCH:-0}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export PYTHONPATH="${REPO_ROOT}${PYTHONPATH:+:${PYTHONPATH}}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

run_python() {
  if [[ "${USE_ACTIVE_CONDA:-0}" == "1" ]]; then
    env PYTHONPATH="${PYTHONPATH}" \
      PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF}" \
      python "$@"
  else
    conda run --no-capture-output -n "${ENV_NAME}" env PYTHONPATH="${PYTHONPATH}" \
      PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF}" \
      python "$@"
  fi
}

cd "${REPO_ROOT}"
mkdir -p "$(dirname "${OUTPUT}")" "$(dirname "${SUMMARY}")"

if [[ "${SKIP_BENCH}" != "1" ]]; then
  # OGB may prompt before downloading ogbn-products. Supplying one "y" keeps
  # first-time runs non-interactive while doing nothing when the dataset exists.
  printf 'y\n' | run_python -u examples/benchmark_products_modes.py \
    --root "${ROOT}" \
    --sample_nodes 0 \
    --epochs "${EPOCHS}" \
    --hidden "${HIDDEN}" \
    --partitioners grinnder \
    --parts "${PARTS}" \
    --modes grinnder_auto \
    --device "${DEVICE}" \
    --host_memory_budget_gb "${HOST_MEMORY_BUDGET_GB}" \
    --output_csv "${OUTPUT}"
fi

SUMMARY_PYTHON="${SUMMARY_PYTHON:-python3}"
if ! command -v "${SUMMARY_PYTHON}" >/dev/null 2>&1; then
  SUMMARY_PYTHON="python"
fi

"${SUMMARY_PYTHON}" - "${OUTPUT}" "${SUMMARY}" <<'PY'
from __future__ import annotations

import csv
import sys
from pathlib import Path

csv_path = Path(sys.argv[1])
summary_path = Path(sys.argv[2])
rows = list(csv.DictReader(csv_path.open()))

def f(value: str, digits: int = 3) -> str:
    if value == "":
        return ""
    return f"{float(value):.{digits}f}"

def pct(value: str) -> str:
    if value == "":
        return ""
    return f"{float(value) * 100:.2f}"

lines = [
    "# OGBN-Products H256 E10 Results",
    "",
    "Generated by:",
    "",
    "```bash",
    "bash scripts/reproduce_products_h256_e10.sh",
    "```",
    "",
    f"CSV: `{csv_path}`",
    "",
    "Time/epoch is the median over 10 training epochs; the minimum epoch time "
    "is included for completeness. Accuracy is measured after the 10th epoch.",
    "",
    "| Partitions | Mode | Cache | Min epoch (s) | Median epoch (s) | 10-epoch Val Acc (%) | 10-epoch Test Acc (%) | Peak CUDA (GB) | State diff vs first row |",
    "|------------|------|-------|---------------|------------------|----------------------|-----------------------|----------------|-----------------------------|",
]

for row in rows:
    mode = "HongTu" if row["mode"] == "hongtu" else "GriNNder auto"
    cache = row["resolved_cache_mode"] or row["cache_mode"]
    lines.append(
        "| {parts} | {mode} | `{cache}` | {min_epoch} | {median_epoch} | "
        "{val} | {test} | {peak} | {diff} |".format(
            parts=row["parts"],
            mode=mode,
            cache=cache,
            min_epoch=f(row["min_epoch_s"]),
            median_epoch=f(row["median_epoch_s"]),
            val=pct(row["val_acc"]),
            test=pct(row["test_acc"]),
            peak=f(row["peak_cuda_gb"]),
            diff=f(row["state_max_diff_vs_ref"], 6),
        )
    )

summary_path.parent.mkdir(parents=True, exist_ok=True)
summary_path.write_text("\n".join(lines) + "\n")
print(f"Wrote {summary_path}")
PY
